### ISSUE TITLE
Faculty Hub

### ISSUE THREAD

**Issue by jhmvin** [jhmvin/Enrollment-Evaluation-Management-System#1]
Add Faculty Hub feature

- Display sections assigned to the currently logged in faculty
- Display also the schedule can be a row extension for that section
- Print the master list of the students from the load_group as PDF
- Export as Excel with the following fields [Student Number] [Full Name Last Name First] [Grade] [Clearance]
- Leave the Grade and Clearance Field as blank
- Can read the exported file for encoding

**Comment by joemardc98** [comment]
do i have a reference to use in reading the exported file for encoding?
