### ISSUE TITLE
Grade History on Credit Tree

### ISSUE THREAD

**Issue by jhmvin** [jhmvin/Enrollment-Evaluation-Management-System#10]
on the table of history of grades add an option to each row to mark a grade as CORRECTION
then update that grade in the database with its status as CORRECTION from being ACCEPTED

**Comment by joemardc98** [comment]
can i add it this way?
![image](https://user-images.githubusercontent.com/33676664/32825098-97a78f00-ca1e-11e7-8fba-0a866ea84f7a.png)

**Comment by jhmvin** [comment]
so ugly make it a check box below the conditionally passed label use JFX Material checkbox

**Comment by joemardc98** [comment]
when checked, can still be unchecked?

**Comment by joemardc98** [comment]
status, is that the grade_state?

**Comment by joemardc98** [comment]
![image](https://user-images.githubusercontent.com/33676664/32826761-a2c57982-ca24-11e7-99e1-d7706a0d5236.png)

**Comment by jhmvin** [comment]
just place it in the right most side of the row after update and date

**Comment by joemardc98** [comment]
status, the grade_state col right?

**Comment by joemardc98** [comment]
done
