### ISSUE TITLE
FIX INCORRECT DATA IN TABLES

### ISSUE THREAD

**Issue by jhmvin** [jhmvin/Enrollment-Evaluation-Management-System#104]
- check all internship type of subject - some of them are in type major
- incorrect prereq of IT 143 of BSIT REVISED (11-12) 1styr 2nd sem
- incorrect subject code LIT 214 into LIT 213 of BSIT REVISED (11-12) 2ndyr 1stsem
- IT 413 must have IT 323 as prereq of BSIT REVISED (11-12) 4thyr 1st sem
- MATH 133 into MATH 113 of BITCT (11-12) 1styr 1stsem
- PE 122 into PE 112 of BITCT (11-12) 1styr 1stsem
- NSTP 2 ROTC/LTS?CWTS into ROTC/LTS/CWTS
- arrangement in 3rd yr 1st sem of BITCT (11-12)
- incorrect lec and lab units in ACT (15-16) 1st yr 2nd sem and 2nd yr 2nd sem
@joemardc98

**Comment by joemardc98** [comment]
done
