### ISSUE TITLE
MARSHAL FORCE LOGOUT

### ISSUE THREAD

**Issue by jhmvin** [jhmvin/Enrollment-Evaluation-Management-System#11]
Add an option in the marshals table in the Linked Manager to delete the session of a marshal
since the app does not allow multiple logins there are instance the marshal will forgot to logout his/her account and then the phone that he/she used is not with him/her

in this scenario the marshal will not be able to use his account therefor a need of force logout is necessary

how to force logout a marshall

update all entries from the **linked_marshall_session** Table with **session_end = null and  status = ONLINE**

update the session end withe the current server time and status will be OFFLINE

**Comment by joemardc98** [comment]
force logout is for every student marshall right?

**Comment by jhmvin** [comment]
place it behind the affiliates combo box

> every row must have a force logout button for each marshall

**Comment by joemardc98** [comment]
i've placed it under remove button
![image](https://user-images.githubusercontent.com/33676664/32823903-c41e645a-ca19-11e7-8fe4-2c2df9a31057.png)

**Comment by joemardc98** [comment]
done
