### ISSUE TITLE
CROSS-ENROLLEE NO ADDING

### ISSUE THREAD

**Issue by jhmvin** [jhmvin/Enrollment-Evaluation-Management-System#12]
> CrossEnrollee Students should not be able to participate in adding and changing of subjects

**Comment by joemardc98** [comment]
how to identify if a student is a cross enrollee?

**Comment by jhmvin** [comment]
Gawa ka bagong student tapos gawin mo siyang cross enrollee sa first evaluation

**Comment by joemardc98** [comment]
done
