### ISSUE TITLE
Asssitant Registrar Override

### ISSUE THREAD

**Issue by jhmvin** [jhmvin/Enrollment-Evaluation-Management-System#13]
> Allow the Assistant Registrar to override

- on the previous case the assistant registrar is not allowed to override
- with this new feature create a random OTP
- insert it to the **otp_generator** table
- HASH the value before insertion
- use the SMS API to send the UNHASHED code to the **sms_server database**
- get the inserted id of the **otp_generator**
- ask the assitant registrar for the code displaying the inserted id as refererence
- hash the input then fetch the otp_generator entry with the id

> Database.connect().opt_generator().getPrimary(**ID HERE**)

- compare the hashed codes if equal then proceed to overriding menu with upload of file

> THE SMS should also contain the reference id of the code

> MAKE this a static function of a CLASS so that when the sms will not work just in case we can comment out few lines to revert back to the previous rules

**Use the classname AssitantRegistrarOverride**

**Comment by joemardc98** [comment]
![image](https://user-images.githubusercontent.com/33676664/32840689-6116a32e-ca53-11e7-83f2-92849b316ec5.png)

**Comment by jhmvin** [comment]
check text wrapping option on labels to enable multiline labels

**Comment by joemardc98** [comment]
highlighted phrase is when you want to resend OTP

![image](https://user-images.githubusercontent.com/33676664/32883309-fc0f8a14-caf1-11e7-88cd-2ec5499586f7.png)

**Comment by joemardc98** [comment]
done

**Comment by jhmvin** [comment]
what does resend does ?

**Comment by joemardc98** [comment]
i already shown you this yesterday. close this again if no other question
