### ISSUE TITLE
FTP transaction should use NON BLOCKING OPERATIONS

### ISSUE THREAD

**Issue by jhmvin** [jhmvin/Enrollment-Evaluation-Management-System#16]
use the updated FTP manager and its non blocking methods

since you didn't use any simple task to wrap upload and downloads to make it non blocking

> Blocking operations are dangerous especially with files on a LAN Based system the transferring of files is dependent on the network speed and the size of the file in cases of slow network connections and large files the program may not respond for a long time resulting in a **PROGRAM NOT RESPONDING warning and crashing**

[Non-Blocking Methods Click Here](https://github.com/jhmvin/Enrollment-Evaluation-Management-System/commit/8ca95e399c47c59c1d625f13c5eb7c8020586ec4)

**Comment by joemardc98** [comment]
done
