### ISSUE TITLE
Assistant Registrar Override 1 min - waiting time for resend OTP

### ISSUE THREAD

**Issue by joemardc98** [jhmvin/Enrollment-Evaluation-Management-System#21]

**Comment by joemardc98** [comment]
like wat you've said, i'll wait for your sample code here haha

**Comment by jhmvin** [comment]
int time = 60; // in seconds and must be a class variable

CronThreadwith interval of 1000{
this.time-- or this.time-=1
if(this.time==0) stop this cron thread then reenable the resend{

else fx thread wrap->{
label.settext(time)
label resend = disable
}
}
