### ISSUE TITLE
Using OTP via SMS Issue

### ISSUE THREAD

**Issue by joemardc98** [jhmvin/Enrollment-Evaluation-Management-System#27]
In changing academic term, admin is the only allowed personnel to request right? And using OTP is the suggested process to accept the said request. The Admin have the power to change any detail of all the faculty user. Changing the contact number of the local registrar into his/her own number to receive the OTP by himself, I think one of the issue in this matter. But we can solve it as my suggestion that in contact number, only the user himself can change his/her own mobile number. and also to make it more private in that info.

**Comment by joemardc98** [comment]
please read @jhmvin

**Comment by jhmvin** [comment]
Local registrar and otp for confirmation

**Comment by jhmvin** [comment]
The administrator will not have any permission in changing academic term

**Comment by joemardc98** [comment]
who will request for changing of acad term? still only the local registrar itself?

**Comment by jhmvin** [comment]
The Local Registrar will be the one to initiate a change in academic term and confirm it using an SMS

This method has been practice as 2FA 2 Factor Authentication in this case this will 2FC 2 Factor Confirmation to assure that the local registrar was intentionally changing the academic term and not only by erratum

[More Information About 2FA](https://www.securenvoy.com/two-factor-authentication/what-is-2fa.shtm)

**Comment by joemardc98** [comment]
can the assistant reg can also request for change? since its a 2FC. in case that the local registrar is not present. or strictly the local registrar only?

**Comment by jhmvin** [comment]
when the assitant registrar request for a change in the academic term the code will be sent to the local registrar after then the local registrar should forward the code to the assistant registrar
