### ISSUE TITLE
Create new Linked Session

### ISSUE THREAD

**Issue by jhmvin** [jhmvin/Enrollment-Evaluation-Management-System#3]
creating new linked_settings entry in update 4 the script is already created

[Here is the code for creating new linked session](https://github.com/jhmvin/Enrollment-Evaluation-Management-System/blob/master/src/update4/org/cict/linked_manager/CreateNewSessionTransaction.java)

**Comment by joemardc98** [comment]
where do exactly the given code must be called?

**Comment by jhmvin** [comment]
Linked Manager @ New Session Tab

**Comment by joemardc98** [comment]
pardon, how to pause a session again? is it the floor cut?
![image](https://user-images.githubusercontent.com/33676664/32975777-0f744694-cc46-11e7-8c60-cff786d141b5.png)

**Comment by jhmvin** [comment]
Yes

**Comment by joemardc98** [comment]
floor cut = 1 if paused?

**Comment by joemardc98** [comment]
can i start again the cluster after pausing?

**Comment by jhmvin** [comment]
Yes

**Comment by joemardc98** [comment]
done
