### ISSUE TITLE
Remove Grade Column in excel export in Section Menu

### ISSUE THREAD

**Issue by jhmvin** [jhmvin/Enrollment-Evaluation-Management-System#34]

**Comment by joemardc98** [comment]
disable import grade?

**Comment by joemardc98** [comment]
in section

**Comment by jhmvin** [comment]
Sa section to yung sa may print schedule pg ngexport kase don may grade column na header

**Comment by jhmvin** [comment]
Excel export code is the same in the faculty hub and section
