### ISSUE TITLE
Usage of TRANSACTION PIN

### ISSUE THREAD

**Issue by jhmvin** [jhmvin/Enrollment-Evaluation-Management-System#38]
For any given transaction eg evaluating adding creating section and other transaction wherein the usage of pin is necessary

**Comment by joemardc98** [comment]
![image](https://user-images.githubusercontent.com/33676664/33163043-6e9212ee-d067-11e7-9dfd-de7882deb348.png)

**Comment by jhmvin** [comment]
Add enter as key
