### ISSUE TITLE
History Of All grades of a student

### ISSUE THREAD

**Issue by jhmvin** [jhmvin/Enrollment-Evaluation-Management-System#4]
Create A PDF report the will show all the grades taken by the student active or inactive and whatever remarks it has the arrangement of grades should follow the hierarchy of the subjects in the curriculum

**Comment by joemardc98** [comment]
![image](https://user-images.githubusercontent.com/33676664/32883501-8dd7b3fe-caf2-11e7-991e-98d110e06dd1.png)

**Comment by joemardc98** [comment]
done
