### ISSUE TITLE
Tutorial Section

### ISSUE THREAD

**Issue by jhmvin** [jhmvin/Enrollment-Evaluation-Management-System#5]
Add filter that only one student is allowed in a tutorial section this feature is **overridable**

**Comment by joemardc98** [comment]
![image](https://user-images.githubusercontent.com/33676664/32831062-193044be-ca32-11e7-8cf6-ad300e618b86.png)

**Comment by joemardc98** [comment]
![image](https://user-images.githubusercontent.com/33676664/32831084-27c7f5bc-ca32-11e7-9aa1-5d62f94cc56e.png)

**Comment by jhmvin** [comment]
ok
