### ISSUE TITLE
Shifting if Grades are not retained

### ISSUE THREAD

**Issue by jhmvin** [jhmvin/Enrollment-Evaluation-Management-System#56]
when shifting instead of just making the active field = "0"
update also the updated by and updated date
and reason_for_update = "Unretained When Shifted"

**Comment by joemardc98** [comment]
when retained is false?

**Comment by joemardc98** [comment]
@jhmvin pls close the issue if you approved the changes

**Comment by jhmvin** [comment]
Reason for update must be Student was shifted and this grade was removed
