### ISSUE TITLE
Sitti don't show again

### ISSUE THREAD

**Issue by jhmvin** [jhmvin/Enrollment-Evaluation-Management-System#7]
since there will be a don't show again feature there should be another way on changing the year level of the students

- Only upward change is allowed
- **Changing of year level backwards requires overriding**

**Comment by joemardc98** [comment]
![image](https://user-images.githubusercontent.com/33676664/32839015-e65599c4-ca4d-11e7-8951-a912495beb26.png)

**Comment by joemardc98** [comment]
done
