### ISSUE TITLE
Checklist BSIT1516.java bug

### ISSUE THREAD

**Issue by jhmvin** [jhmvin/Enrollment-Evaluation-Management-System#71]
https://github.com/jhmvin/Enrollment-Evaluation-Management-System/commit/0d8582fbcc6d15ebf440cfbe2e6d84735d2ca0e6#diff-94b73050864216d8130b0c176d855b4aR185

Segment of this code is throwing an error when printing checlist of student with CURRICULUM of actrev2

**Comment by jhmvin** [comment]
just surrounded it with try catch temporarily

**Comment by jhmvin** [comment]
See line 185

**Comment by joemardc98** [comment]
added checking for study years to avoid null in pdf table creator
