### ISSUE TITLE
NOTICE: Clone Method Added

### ISSUE THREAD

**Issue by jhmvin** [jhmvin/Enrollment-Evaluation-Management-System#72]
Refer to this commit:
https://github.com/jhmvin/Enrollment-Evaluation-Management-System/commit/513716dca54804192292d0350ba19c103b0f9383

This class was refactored to create precision object cloning

https://github.com/jhmvin/Enrollment-Evaluation-Management-System/blob/master/src/org/cict/evaluation/student/credit/CreditEncode.java

All mappings are now integrated with copy() method that allows to copy values for easy updating
![copy](https://user-images.githubusercontent.com/30278929/33514743-3c8729c2-d794-11e7-82ab-42d4165e1602.PNG)

**Comment by joemardc98** [comment]
<3
