### ISSUE TITLE
Recovery Question Invalid filter

### ISSUE THREAD

**Issue by jhmvin** [jhmvin/Enrollment-Evaluation-Management-System#74]
allow all type of input in the ascii character set

http://ee.hawaii.edu/~tep/EE160/Book/chap4/subsection2.1.1.1.html

example what is your favorite book

Tuesdays with morrie

says invalid character even if that's really the title of the book

this might be applicable both for registration and in the creation of admin account using the sys account

**Comment by joemardc98** [comment]
filter for the answer
