### ISSUE TITLE
Section max students OVERRIDABLE

### ISSUE THREAD

**Issue by jhmvin** [jhmvin/Enrollment-Evaluation-Management-System#8]
allow to override max population of a section

**Comment by joemardc98** [comment]
i think i'm done w/ this
![image](https://user-images.githubusercontent.com/33676664/32827105-f417c050-ca25-11e7-882a-30bf15bdab04.png)

![image](https://user-images.githubusercontent.com/33676664/32827125-06a8aa04-ca26-11e7-846d-af2b822fd296.png)

**Comment by jhmvin** [comment]
ok
