### ISSUE TITLE
Add Validation in Eval and Adding for Co-Requisite

### ISSUE THREAD

**Issue by joemardc98** [jhmvin/Enrollment-Evaluation-Management-System#89]

**Comment by jhmvin** [comment]
https://github.com/jhmvin/Enrollment-Evaluation-Management-System/commit/4f9734dab8d43f432633503e6d19ae9a78a16b91

please send the database and testing information

**Comment by jhmvin** [comment]
COREQ
https://github.com/jhmvin/Enrollment-Evaluation-Management-System/commit/b85f25701460881b20cb3c32e32d2c9f22c07de9
