### ISSUE TITLE
Fix the following table in the production database

### ISSUE THREAD

**Issue by jhmvin** [jhmvin/Enrollment-Evaluation-Management-System#94]
- curriculum_requisite_ext: make removed date as null
- student: updated date

**Comment by joemardc98** [comment]
check all internship type of subject - some of them are in type major

**Comment by joemardc98** [comment]
incorrect prereq of IT 143 of BSIT REVISED (11-12) 1styr 2nd sem

**Comment by joemardc98** [comment]
incorrect subject code LIT 214 into LIT 213 of BSIT REVISED (11-12)  2ndyr 1stsem

**Comment by joemardc98** [comment]
IT 413 must have IT 323 as prereq  of BSIT REVISED (11-12) 4thyr 1st sem

**Comment by joemardc98** [comment]
MATH 133 into MATH 113 of BITCT (11-12) 1styr 1stsem

**Comment by joemardc98** [comment]
PE 122 into PE 112  of BITCT (11-12) 1styr 1stsem

**Comment by joemardc98** [comment]
NSTP 2 ROTC/LTS?CWTS into ROTC/LTS/CWTS

**Comment by joemardc98** [comment]
arrangement in 3rd yr 1st sem of  BITCT (11-12)

**Comment by joemardc98** [comment]
incorrect lec and lab units in ACT (15-16) 1st yr 2nd sem and 2nd yr 2nd sem
